server:
  port: 5000

spring:
  application:
    name: app
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

jwt:
  secret: 2a323d19c4c1434893dcdc5defb305c5
  expire: 1

secure:
  ignored:
    anonymous:
      - "/login"
    permit:
      - "/favicon.ico"
      - "/register/**"
      - "/product/**"
      - "/pay/**"
