spring:
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://192.168.43.2:3306/zh_mall?serverTimezone=UTC&allowMultiQueries=true
  #    username: root
  #    password: root
  # ShardingSphere-JDBC 配置主从同步
  shardingsphere:
    datasource:
      names: master, slave-01
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://master.com:3306/zh_mall?serverTimezone=UTC&allowMultiQueries=true
        username: root
        password: root
        data-source-properties:
          useLocalSessionState: false
      slave-01:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://slave.com:3306/zh_mall?serverTimezone=UTC&allowMultiQueries=true
        username: root
        password: root
    rules:
      readwrite-splitting:
        data-sources:
          readwrite01:
            type: Static
            props:
              write-data-source-name: master
              read-data-source-names: slave-01
              load-balancer-name: readwrite-lb
        load-balancers:
          readwrite-lb:
            type: ROUND_ROBIN
    props:
      sql-show: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    host: 192.168.43.2
    port: 6379
  rabbitmq:
    host: 192.168.43.2
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual

redisson:
  address: redis://192.168.43.2:6379

thread-pool:
  core-pool-size: 12
  max-pool-size: 24
  work-queue-size: 1000
  keep-alive-seconds: 300

alipay:
  gateway: alipayGateway
  notify-url: notifyUrl
  return-url: returnUrl
  app-id: you appId
  app-private-key: you privateKey
  alipay-public-key: you alipayPublicKey

logstash:
  host: 192.168.43.2
