spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.2:3306/zh_mall?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: root

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

  redis:
    host: 192.168.43.2
    port: 6379

  rabbitmq:
    host: 192.168.43.2
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

jwt:
  secret: 2a323d19c4c1434893dcdc5defb305c5
  expire: 1

redisson:
  address: redis://192.168.43.2:6379

secure:
  ignored:
    anonymous:
      - "/login"
    permit:
      - "/favicon.ico"
      - "/register/**"
      - "/product/**"

thread-pool:
  core-pool-size: 12
  max-pool-size: 24
  work-queue-size: 1000
  keep-alive-seconds: 300
