server:
  port: 6000
  servlet:
    context-path: /admin

spring:
  application:
    name: admin
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

jwt:
  secret: 3e900df3f1ba461c92ddc20d014dfc34
  expire: 1

secure:
  ignored:
    anonymous:
      - "/login"
    permit:
      - "/favicon.ico"
