server:
  port: 5000

spring:
  application:
    name: app
  profiles:
    active: dev
  redis:
    host: ${zh-mall.redis.host}
    port: ${zh-mall.redis.port:6379}
    password: ${zh-mall.redis.password}
  rabbitmq:
    host: ${zh-mall.rabbitmq.host}
    port: ${zh-mall.rabbitmq.port:5672}
    username: ${zh-mall.rabbitmq.username}
    password: ${zh-mall.rabbitmq.password}
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

redisson:
  address: redis://${zh-mall.redis.host}:${zh-mall.redis.port:6379}
  password: ${zh-mall.redis.password}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

jwt:
  secret: 2a323d19c4c1434893dcdc5defb305c5
  expire: 1

secure:
  ignored:
    anonymous:
      - /auth/login/**
    permit:
      - /favicon.ico
      - /auth/register/**
      - /user/info
      - /product/**
      - /coupon/**
      - /pay/**

logging:
  config: classpath:logback-spring.xml
  pattern:
    dateformat: ${spring.jackson.date-format}
