spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yml
  data:
    redis:
      host: 192.168.43.2
      port: 6379
      password: redis-password
  rabbitmq:
    host: 192.168.43.2
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

redisson:
  address: redis://192.168.43.2:6379
  password: redis-password

thread-pool:
  core-pool-size: 12
  max-pool-size: 24
  work-queue-size: 1000
  keep-alive-seconds: 300

ali:
  pay:
    gateway: alipay-gateway
    app-id: your-app-id
    app-private-key: your-private-key
    alipay-public-key: your-alipay-public-key
    notify-url: notify-url
    return-url: return-url
  oss:
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    bucket-domain: https://your-bucket.oss-cn-shenzhen.aliyuncs.com
    access-key-id: your-access-key-id
    access-key-secret: your-access-key-secret
    bucket: your-bucket
  auth:
    gateway: https://openapi.alipay.com/gateway.do
    app-id: your-app-id
    app-private-key: your-app-private-key
    alipay-public-key: your-alipay-public-key

logstash:
  host: 192.168.43.2
