spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.2:3306/zh_mall?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: root
    hikari:
      minimum-idle: 12
      maximum-pool-size: 24
      connection-timeout: 60000
  redis:
    host: 192.168.43.2
    port: 6379
    password: redis-password
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

thread-pool:
  core-pool-size: 12
  max-pool-size: 24
  work-queue-size: 1000
  keep-alive-seconds: 300

ali:
  oss:
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    bucket-domain: https://your-bucket.oss-cn-shenzhen.aliyuncs.com
    access-key-id: your-access-key-id
    access-key-secret: your-access-key-secret
    bucket: your-bucket

logstash:
  host: 192.168.43.2
