server:
  port: 6000
  servlet:
    context-path: /admin

spring:
  application:
    name: admin
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

jwt:
  secret: 3e900df3f1ba461c92ddc20d014dfc34
  expire: 1

secure:
  ignored:
    anonymous:
      - /auth/login
    permit:
      - /favicon.ico

logging:
  config: classpath:logback-spring.xml
  pattern:
    dateformat: ${spring.jackson.date-format}
