spring:
  rabbitmq:
    host: 192.168.43.2
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

thread-pool:
  core-pool-size: 12
  max-pool-size: 24
  work-queue-size: 1000
  keep-alive-seconds: 300

elastic:
  address:
    - 192.168.43.2:9200

logstash:
  host: 192.168.43.2
