server:
  port: 7000

spring:
  application:
    name: search
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

logging:
  config: classpath:logback-spring.xml
  pattern:
    dateformat: ${spring.jackson.date-format}
