spring:
  rabbitmq:
    host: 8.217.21.159
    port: 5672
    username: guest
    password: 0508@qq.com
    virtual-host: /
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

elastic:
  address:
    - 192.168.43.2:9200

logstash:
  host: 192.168.43.2
